# SPDX-FileCopyrightText: 2026 Spencer
# SPDX-License-Identifier: AGPL-3.0-only

version = 1
SPDX-PackageName = "Aletheia"
SPDX-PackageDownloadLocation = "https://github.com/Spencer-0003/aletheia"

[[annotations]]
path = "screenshots/*.png"
precedence = "override"
SPDX-FileCopyrightText = "2025 Spencer"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["ui/locale/aletheia.pot", "ui/locale/*/LC_MESSAGES/aletheia.po"]
precedence = "override"
SPDX-FileCopyrightText = "2025-2026 Spencer"
SPDX-License-Identifier = "AGPL-3.0-only"
