# SPDX-FileCopyrightText: 2026 Spencer
# SPDX-License-Identifier: AGPL-3.0-only

version = 1
SPDX-PackageName = "Aletheia"
SPDX-PackageDownloadLocation = "https://github.com/Spencer-0003/aletheia"

[[annotations]]
path = "ui/locale/*/LC_MESSAGES/aletheia.po"
precedence = "override"
SPDX-License-Identifier = "AGPL-3.0-only"
