# SPDX-FileCopyrightText: 2026 Spencer
# SPDX-License-Identifier: AGPL-3.0-only

version = 1
SPDX-PackageName = "Aletheia"
SPDX-PackageDownloadLocation = "https://github.com/Spencer-0003/aletheia"

[[annotations]]
path = ["resources/logo/moe.spencer.Aletheia.png", "resources/logo/scalable.svg", "resources/logo/windows.ico", "resources/mac/aletheia.icns"]
precedence = "override"
SPDX-FileCopyrightText = "2025 Spencer"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = ["renovate.json", "screenshots/*.png"]
precedence = "override"
SPDX-FileCopyrightText = "2025 Spencer"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["Cargo.lock", "ui/locale/aletheia.pot", "ui/locale/*/LC_MESSAGES/aletheia.po"]
precedence = "override"
SPDX-FileCopyrightText = "2025-2026 Spencer"
SPDX-License-Identifier = "AGPL-3.0-only"

[[annotations]]
path = ["ui/fonts/Inter/Inter.ttc", "ui/fonts/Inter/InterVariable-Italic.ttf", "ui/fonts/Inter/InterVariable.ttf"]
precedence = "override"
SPDX-FileCopyrightText = "2017 Rasmus Andersson"
SPDX-License-Identifier = "OFL-1.1"
